# Generated by Django 4.2.4 on 2023-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_alter_article_options_scope_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                null=True, through="articles.Scope", to="articles.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
