# Generated by Django 4.2.4 on 2023-08-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("subject", models.CharField(max_length=10, verbose_name="Предмет")),
            ],
            options={
                "verbose_name": "Учитель",
                "verbose_name_plural": "Учителя",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                ("st_group", models.CharField(max_length=10, verbose_name="Класс")),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="students", to="school.teacher"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
    ]
