# Generated by Django 4.2.3 on 2023-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Температура"
            ),
        ),
    ]
