# Generated by Django 4.2.3 on 2023-09-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0002_alter_measurement_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="sensor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="measurement.sensor",
                verbose_name="Датчик",
            ),
        ),
    ]
